### ISSUE TITLE
Please Creating Releases

### ISSUE THREAD

**Issue by somelib** [mohamedhelal/arabTemplate#9]
please create releases to active composer stable downloads

**Comment by mohamedhelal** [comment]
how i can create releases to active composer stable downloads

**Comment by somelib** [comment]
See https://help.github.com/articles/creating-releases/
And update package on https://packagist.org/

**Comment by mohamedhelal** [comment]
Thank you very library will help you and others

**Comment by mohamedhelal** [comment]
i us Google translator

**Comment by somelib** [comment]
بالتوفيق الموضوع سهل جدا بانتظار صدور نسخة مستقرة 😊
